site_name: gba-doc
docs_dir: gba-doc
site_url: https://merryhime.github.io/gba-doc/
repo_url: https://github.com/merryhime/gba-doc"

theme:
  name: null
  custom_dir: cinder
  colorscheme: github

markdown_extensions:
  - footnotes
  - tables
  - toc:
      permalink: true

plugins:
  - search
  - roamlinks
